web:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: ips-test
        DB_USERNAME: bucho
        DB_PASSWORD: bucho
        DB_CONNECTION: mysql

db:
    image: mysql
    ports:
        - 3306:3306
    volumes:
        - ./data:/var/lib/mysql
    environment:
        # with mysql
        MYSQL_ROOT_PASSWORD: bucho
        MYSQL_DATABASE: ips-test
        MYSQL_USER: bucho
        MYSQL_PASSWORD: bucho