web:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    links:
        - db



db:
    image: mysql
    ports:
        - 3306:3306
    volumes:
        - ./data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_RANDOM_ROOT_PASSWORD: root
#        # with mysql
        MYSQL_DATABASE: ips-test
        MYSQL_USER: paul
        MYSQL_PASSWORD: paul

        # with postgres
        POSTGRES_DB: ips-test
        POSTGRES_USER: paul
        POSTGRES_PASSWORD: paul